Add a re-entrancy guard to exitRuntime() (#26838)
Add a re-entrancy guard to exitRuntime(), since such re-entrancy is seen
to happen if an atexit() handler throws a JS exception (e.g.
RuntimeError: index out of bounds)

Separated out from #26835.